name: Build and publish image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sign In
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Prepare original images
        run: |
          docker pull php:7.4-fpm-alpine \
            & docker pull php:7.4-apache

      - name: Build
        run: |
          docker build -t php74-fpm .
          docker build -t php74-composer --build-arg INSTALL_COMPOSER . \
            & docker build -t php74-apache -f php-apache.Dockerfile .

      - name: Publish images
        run: |
          docker tag php74-fpm parsilver/php-7.4:latest
          docker tag php74-composer parsilver/php-7.4:composer
          docker tag php74-apache parsilver/php-7.4:apache
          docker push parsilver/php-7.4:latest \
            & docker push parsilver/php-7.4:composer \
            & docker push parsilver/php-7.4:apache